/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InspectorRouteImport } from './routes/inspector'
import { Route as DocIdRouteImport } from './routes/doc.$id'
import { Route as ReadIdRouteImport } from './routes/read.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorRoute = InspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const DocIdRoute = DocIdRouteImport.update({
  id: '/doc/$id',
  path: '/doc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadIdRoute = ReadIdRouteImport.update({
  id: '/read/$id',
  path: '/read/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inspector': typeof InspectorRoute
  '/doc/$id': typeof DocIdRoute
  '/read/$id': typeof ReadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inspector': typeof InspectorRoute
  '/doc/$id': typeof DocIdRoute
  '/read/$id': typeof ReadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inspector': typeof InspectorRoute
  '/doc/$id': typeof DocIdRoute
  '/read/$id': typeof ReadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inspector' | '/doc/$id' | '/read/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inspector' | '/doc/$id' | '/read/$id'
  id: '__root__' | '/' | '/inspector' | '/doc/$id' | '/read/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InspectorRoute: typeof InspectorRoute
  DocIdRoute: typeof DocIdRoute
  ReadIdRoute: typeof ReadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector': {
      id: '/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof InspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$id': {
      id: '/doc/$id'
      path: '/doc/$id'
      fullPath: '/doc/$id'
      preLoaderRoute: typeof DocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$id': {
      id: '/read/$id'
      path: '/read/$id'
      fullPath: '/read/$id'
      preLoaderRoute: typeof ReadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InspectorRoute: InspectorRoute,
  DocIdRoute: DocIdRoute,
  ReadIdRoute: ReadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
